# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: annotations_converter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='annotations_converter.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x61nnotations_converter.proto\"\xd3\x01\n\x11\x43onversionRequest\x12\x10\n\x08\x64\x65stpath\x18\x01 \x01(\t\x12\x13\n\x0brecord_name\x18\x02 \x01(\t\x12\r\n\x05img_w\x18\x03 \x01(\t\x12\r\n\x05img_h\x18\x04 \x01(\t\x12\x12\n\ndataset_id\x18\x05 \x01(\t\x12\x18\n\x10\x61nnotations_list\x18\x06 \x03(\t\x12\x17\n\x0f\x63onversion_type\x18\x07 \x01(\t\x12\x18\n\x10train_percentage\x18\x08 \x01(\t\x12\x18\n\x10test_train_split\x18\t \x01(\t\"9\n\x10\x43onversionsReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rconversion_id\x18\x02 \x01(\t2U\n\x14\x41nnotationsConverter\x12=\n\x12\x43onvertAnnotations\x12\x12.ConversionRequest\x1a\x11.ConversionsReply\"\x00\x62\x06proto3')
)




_CONVERSIONREQUEST = _descriptor.Descriptor(
  name='ConversionRequest',
  full_name='ConversionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='destpath', full_name='ConversionRequest.destpath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_name', full_name='ConversionRequest.record_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_w', full_name='ConversionRequest.img_w', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_h', full_name='ConversionRequest.img_h', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset_id', full_name='ConversionRequest.dataset_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annotations_list', full_name='ConversionRequest.annotations_list', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conversion_type', full_name='ConversionRequest.conversion_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_percentage', full_name='ConversionRequest.train_percentage', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_train_split', full_name='ConversionRequest.test_train_split', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=243,
)


_CONVERSIONSREPLY = _descriptor.Descriptor(
  name='ConversionsReply',
  full_name='ConversionsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ConversionsReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conversion_id', full_name='ConversionsReply.conversion_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=302,
)

DESCRIPTOR.message_types_by_name['ConversionRequest'] = _CONVERSIONREQUEST
DESCRIPTOR.message_types_by_name['ConversionsReply'] = _CONVERSIONSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConversionRequest = _reflection.GeneratedProtocolMessageType('ConversionRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONVERSIONREQUEST,
  __module__ = 'annotations_converter_pb2'
  # @@protoc_insertion_point(class_scope:ConversionRequest)
  ))
_sym_db.RegisterMessage(ConversionRequest)

ConversionsReply = _reflection.GeneratedProtocolMessageType('ConversionsReply', (_message.Message,), dict(
  DESCRIPTOR = _CONVERSIONSREPLY,
  __module__ = 'annotations_converter_pb2'
  # @@protoc_insertion_point(class_scope:ConversionsReply)
  ))
_sym_db.RegisterMessage(ConversionsReply)



_ANNOTATIONSCONVERTER = _descriptor.ServiceDescriptor(
  name='AnnotationsConverter',
  full_name='AnnotationsConverter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=304,
  serialized_end=389,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertAnnotations',
    full_name='AnnotationsConverter.ConvertAnnotations',
    index=0,
    containing_service=None,
    input_type=_CONVERSIONREQUEST,
    output_type=_CONVERSIONSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANNOTATIONSCONVERTER)

DESCRIPTOR.services_by_name['AnnotationsConverter'] = _ANNOTATIONSCONVERTER

# @@protoc_insertion_point(module_scope)
