# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import annotations_converter_pb2 as annotations__converter__pb2


class AnnotationsConverterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ConvertAnnotations = channel.unary_unary(
        '/AnnotationsConverter/ConvertAnnotations',
        request_serializer=annotations__converter__pb2.ConversionRequest.SerializeToString,
        response_deserializer=annotations__converter__pb2.ConversionsReply.FromString,
        )


class AnnotationsConverterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ConvertAnnotations(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnnotationsConverterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ConvertAnnotations': grpc.unary_unary_rpc_method_handler(
          servicer.ConvertAnnotations,
          request_deserializer=annotations__converter__pb2.ConversionRequest.FromString,
          response_serializer=annotations__converter__pb2.ConversionsReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AnnotationsConverter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
